/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface ContextConsumerProps {
  
  /**  */
  context?: Components.ContextConsumer["context"]
  
  /**  */
  renderer?: Components.ContextConsumer["renderer"]
  
  /**  */
  subscribe?: Components.ContextConsumer["subscribe"]
}

interface ContextConsumerEvents {
  
}

interface ContextConsumerSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let context_consumer;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			context_consumer = element("context-consumer");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, context_consumer, anchor);

			if (default_slot) {
				default_slot.m(context_consumer, null);
			}

			/*context_consumer_binding*/ ctx[8](context_consumer);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(context_consumer);
			if (default_slot) default_slot.d(detaching);
			/*context_consumer_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { context = undefined } = $$props;
	let { renderer = undefined } = $$props;
	let { subscribe = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(5, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function context_consumer_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("context" in $$props) $$invalidate(1, context = $$props.context);
		if ("renderer" in $$props) $$invalidate(2, renderer = $$props.renderer);
		if ("subscribe" in $$props) $$invalidate(3, subscribe = $$props.subscribe);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, context*/ 34) {
			$: if (__mounted) setProp("context", context);
		}

		if ($$self.$$.dirty & /*__mounted, renderer*/ 36) {
			$: if (__mounted) setProp("renderer", renderer);
		}

		if ($$self.$$.dirty & /*__mounted, subscribe*/ 40) {
			$: if (__mounted) setProp("subscribe", subscribe);
		}
	};

	return [
		__ref,
		context,
		renderer,
		subscribe,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		context_consumer_binding
	];
}

class ContextConsumer extends SvelteComponent {
  $$prop_def: ContextConsumerProps;
  $$events_def: ContextConsumerEvents;
  $$slot_def: ContextConsumerSlots;

  $on<K extends keyof ContextConsumerEvents>(type: K, callback: (e: ContextConsumerEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<ContextConsumerProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			context: 1,
			renderer: 2,
			subscribe: 3,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLContextConsumerElement | undefined {
		return this.$$.ctx[4];
	}
}

export default ContextConsumer;