/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface GetAQuoteExampleProps {
  
}

interface GetAQuoteExampleEvents {
  
}

interface GetAQuoteExampleSlots {
  default: any
}
  
/* generated by Svelte v3.32.3 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let get_a_quote_example;
	let current;
	const default_slot_template = /*#slots*/ ctx[3].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[2], null);

	return {
		c() {
			get_a_quote_example = element("get-a-quote-example");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, get_a_quote_example, anchor);

			if (default_slot) {
				default_slot.m(get_a_quote_example, null);
			}

			/*get_a_quote_example_binding*/ ctx[4](get_a_quote_example);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 4) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[2], dirty, null, null);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(get_a_quote_example);
			if (default_slot) default_slot.d(detaching);
			/*get_a_quote_example_binding*/ ctx[4](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function get_a_quote_example_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("$$scope" in $$props) $$invalidate(2, $$scope = $$props.$$scope);
	};

	return [__ref, getWebComponent, $$scope, slots, get_a_quote_example_binding];
}

class GetAQuoteExample extends SvelteComponent {
  $$prop_def: GetAQuoteExampleProps;
  $$events_def: GetAQuoteExampleEvents;
  $$slot_def: GetAQuoteExampleSlots;

  $on<K extends keyof GetAQuoteExampleEvents>(type: K, callback: (e: GetAQuoteExampleEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<GetAQuoteExampleProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { getWebComponent: 1 });
	}

	get getWebComponent(): HTMLGetAQuoteExampleElement | undefined {
		return this.$$.ctx[1];
	}
}

export default GetAQuoteExample;