/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntArticleLinkProps {
  
  /**  */
  href?: Components.SntArticleLink["href"]
  
  /**  */
  copy?: Components.SntArticleLink["copy"]
  
  /**  */
  ariaLabel?: Components.SntArticleLink["ariaLabel"]
  
  /**  */
  hiddenTitle?: Components.SntArticleLink["hiddenTitle"]
}

interface SntArticleLinkEvents {
  
}

interface SntArticleLinkSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_article_link;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			snt_article_link = element("snt-article-link");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_article_link, "href", /*href*/ ctx[0]);
			set_custom_element_data(snt_article_link, "copy", /*copy*/ ctx[1]);
			set_custom_element_data(snt_article_link, "aria-label", /*ariaLabel*/ ctx[2]);
			set_custom_element_data(snt_article_link, "hidden-title", /*hiddenTitle*/ ctx[3]);
		},
		m(target, anchor) {
			insert(target, snt_article_link, anchor);

			if (default_slot) {
				default_slot.m(snt_article_link, null);
			}

			/*snt_article_link_binding*/ ctx[8](snt_article_link);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}

			if (!current || dirty & /*href*/ 1) {
				set_custom_element_data(snt_article_link, "href", /*href*/ ctx[0]);
			}

			if (!current || dirty & /*copy*/ 2) {
				set_custom_element_data(snt_article_link, "copy", /*copy*/ ctx[1]);
			}

			if (!current || dirty & /*ariaLabel*/ 4) {
				set_custom_element_data(snt_article_link, "aria-label", /*ariaLabel*/ ctx[2]);
			}

			if (!current || dirty & /*hiddenTitle*/ 8) {
				set_custom_element_data(snt_article_link, "hidden-title", /*hiddenTitle*/ ctx[3]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_article_link);
			if (default_slot) default_slot.d(detaching);
			/*snt_article_link_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { href = undefined } = $$props;
	let { copy = undefined } = $$props;
	let { ariaLabel = undefined } = $$props;
	let { hiddenTitle = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(4, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_article_link_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(4, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("href" in $$props) $$invalidate(0, href = $$props.href);
		if ("copy" in $$props) $$invalidate(1, copy = $$props.copy);
		if ("ariaLabel" in $$props) $$invalidate(2, ariaLabel = $$props.ariaLabel);
		if ("hiddenTitle" in $$props) $$invalidate(3, hiddenTitle = $$props.hiddenTitle);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	return [
		href,
		copy,
		ariaLabel,
		hiddenTitle,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_article_link_binding
	];
}

class SntArticleLink extends SvelteComponent {
  $$prop_def: SntArticleLinkProps;
  $$events_def: SntArticleLinkEvents;
  $$slot_def: SntArticleLinkSlots;

  $on<K extends keyof SntArticleLinkEvents>(type: K, callback: (e: SntArticleLinkEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntArticleLinkProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			href: 0,
			copy: 1,
			ariaLabel: 2,
			hiddenTitle: 3,
			getWebComponent: 5
		});
	}

	get getWebComponent(): HTMLSntArticleLinkElement | undefined {
		return this.$$.ctx[5];
	}
}

export default SntArticleLink;