/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntAccordionGroupProps {
  
  /**  */
  multiExpand?: Components.SntAccordionGroup["multiExpand"]
}

interface SntAccordionGroupEvents {
  
}

interface SntAccordionGroupSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_accordion_group;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			snt_accordion_group = element("snt-accordion-group");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_accordion_group, "multi-expand", /*multiExpand*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, snt_accordion_group, anchor);

			if (default_slot) {
				default_slot.m(snt_accordion_group, null);
			}

			/*snt_accordion_group_binding*/ ctx[8](snt_accordion_group);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}

			if (!current || dirty & /*multiExpand*/ 1) {
				set_custom_element_data(snt_accordion_group, "multi-expand", /*multiExpand*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_accordion_group);
			if (default_slot) default_slot.d(detaching);
			/*snt_accordion_group_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { multiExpand = undefined } = $$props;
	const expandAll = (...args) => __ref.expandAll(...args);
	const collapseAll = (...args) => __ref.collapseAll(...args);
	const addAccordion = (...args) => __ref.addAccordion(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_accordion_group_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("multiExpand" in $$props) $$invalidate(0, multiExpand = $$props.multiExpand);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	return [
		multiExpand,
		__ref,
		expandAll,
		collapseAll,
		addAccordion,
		getWebComponent,
		$$scope,
		slots,
		snt_accordion_group_binding
	];
}

class SntAccordionGroup extends SvelteComponent {
  $$prop_def: SntAccordionGroupProps;
  $$events_def: SntAccordionGroupEvents;
  $$slot_def: SntAccordionGroupSlots;

  $on<K extends keyof SntAccordionGroupEvents>(type: K, callback: (e: SntAccordionGroupEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntAccordionGroupProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			multiExpand: 0,
			expandAll: 2,
			collapseAll: 3,
			addAccordion: 4,
			getWebComponent: 5
		});
	}

	
  /**  */
 get expandAll(): Components.SntAccordionGroup["expandAll"] {
		return this.$$.ctx[2];
	}

	
  /**  */
 get collapseAll(): Components.SntAccordionGroup["collapseAll"] {
		return this.$$.ctx[3];
	}

	
  /**  */
 get addAccordion(): Components.SntAccordionGroup["addAccordion"] {
		return this.$$.ctx[4];
	}

	get getWebComponent(): HTMLSntAccordionGroupElement | undefined {
		return this.$$.ctx[5];
	}
}

export default SntAccordionGroup;