/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntBackdropProps {
  
  /** If `true`, the backdrop can be clicked and will emit `ionBackdropTap` event. */
  tappable?: Components.SntBackdrop["tappable"]
  
  /** If `true`, the backdroo will stop propagation on tap */
  stopPropagation?: Components.SntBackdrop["stopPropagation"]
}

interface SntBackdropEvents {
  
  /** Emitted when the backdrop is tapped */
  sntBackdropTap: Parameters<JSX.SntBackdrop["onSntBackdropTap"]>[0]
}

interface SntBackdropSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_backdrop;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			snt_backdrop = element("snt-backdrop");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, snt_backdrop, anchor);

			if (default_slot) {
				default_slot.m(snt_backdrop, null);
			}

			/*snt_backdrop_binding*/ ctx[8](snt_backdrop);
			current = true;

			if (!mounted) {
				dispose = listen(snt_backdrop, "sntBackdropTap", /*onEvent*/ ctx[1]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_backdrop);
			if (default_slot) default_slot.d(detaching);
			/*snt_backdrop_binding*/ ctx[8](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { tappable = undefined } = $$props;
	let { stopPropagation = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(5, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_backdrop_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("tappable" in $$props) $$invalidate(2, tappable = $$props.tappable);
		if ("stopPropagation" in $$props) $$invalidate(3, stopPropagation = $$props.stopPropagation);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, tappable*/ 36) {
			$: if (__mounted) setProp("tappable", tappable);
		}

		if ($$self.$$.dirty & /*__mounted, stopPropagation*/ 40) {
			$: if (__mounted) setProp("stopPropagation", stopPropagation);
		}
	};

	return [
		__ref,
		onEvent,
		tappable,
		stopPropagation,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		snt_backdrop_binding
	];
}

class SntBackdrop extends SvelteComponent {
  $$prop_def: SntBackdropProps;
  $$events_def: SntBackdropEvents;
  $$slot_def: SntBackdropSlots;

  $on<K extends keyof SntBackdropEvents>(type: K, callback: (e: SntBackdropEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntBackdropProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			tappable: 2,
			stopPropagation: 3,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLSntBackdropElement | undefined {
		return this.$$.ctx[4];
	}
}

export default SntBackdrop;