/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntConnectOffersProps {
  
  /**  */
  offerAvailable?: Components.SntConnectOffers["offerAvailable"]
  
  /**  */
  logoSources?: Components.SntConnectOffers["logoSources"]
  
  /**  */
  altTag?: Components.SntConnectOffers["altTag"]
  
  /**  */
  offerTitle?: Components.SntConnectOffers["offerTitle"]
  
  /**  */
  titleString?: Components.SntConnectOffers["titleString"]
  
  /**  */
  href?: Components.SntConnectOffers["href"]
  
  /**  */
  target?: Components.SntConnectOffers["target"]
  
  /**  */
  description?: Components.SntConnectOffers["description"]
  
  /**  */
  buttonLabel?: Components.SntConnectOffers["buttonLabel"]
  
  /**  */
  ariaLabel?: Components.SntConnectOffers["ariaLabel"]
  
  /**  */
  actionReference?: Components.SntConnectOffers["actionReference"]
  
  /**  */
  actionData?: Components.SntConnectOffers["actionData"]
  
  /**  */
  modalData?: Components.SntConnectOffers["modalData"]
}

interface SntConnectOffersEvents {
  
}

interface SntConnectOffersSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_connect_offers;
	let current;
	const default_slot_template = /*#slots*/ ctx[16].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[15], null);

	return {
		c() {
			snt_connect_offers = element("snt-connect-offers");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_connect_offers, "offer-available", /*offerAvailable*/ ctx[0]);
			set_custom_element_data(snt_connect_offers, "logo-sources", /*logoSources*/ ctx[1]);
			set_custom_element_data(snt_connect_offers, "alt-tag", /*altTag*/ ctx[2]);
			set_custom_element_data(snt_connect_offers, "offer-title", /*offerTitle*/ ctx[3]);
			set_custom_element_data(snt_connect_offers, "title-string", /*titleString*/ ctx[4]);
			set_custom_element_data(snt_connect_offers, "href", /*href*/ ctx[5]);
			set_custom_element_data(snt_connect_offers, "target", /*target*/ ctx[6]);
			set_custom_element_data(snt_connect_offers, "description", /*description*/ ctx[7]);
			set_custom_element_data(snt_connect_offers, "button-label", /*buttonLabel*/ ctx[8]);
			set_custom_element_data(snt_connect_offers, "aria-label", /*ariaLabel*/ ctx[9]);
			set_custom_element_data(snt_connect_offers, "action-reference", /*actionReference*/ ctx[10]);
			set_custom_element_data(snt_connect_offers, "action-data", /*actionData*/ ctx[11]);
			set_custom_element_data(snt_connect_offers, "modal-data", /*modalData*/ ctx[12]);
		},
		m(target, anchor) {
			insert(target, snt_connect_offers, anchor);

			if (default_slot) {
				default_slot.m(snt_connect_offers, null);
			}

			/*snt_connect_offers_binding*/ ctx[17](snt_connect_offers);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 32768) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[15], dirty, null, null);
				}
			}

			if (!current || dirty & /*offerAvailable*/ 1) {
				set_custom_element_data(snt_connect_offers, "offer-available", /*offerAvailable*/ ctx[0]);
			}

			if (!current || dirty & /*logoSources*/ 2) {
				set_custom_element_data(snt_connect_offers, "logo-sources", /*logoSources*/ ctx[1]);
			}

			if (!current || dirty & /*altTag*/ 4) {
				set_custom_element_data(snt_connect_offers, "alt-tag", /*altTag*/ ctx[2]);
			}

			if (!current || dirty & /*offerTitle*/ 8) {
				set_custom_element_data(snt_connect_offers, "offer-title", /*offerTitle*/ ctx[3]);
			}

			if (!current || dirty & /*titleString*/ 16) {
				set_custom_element_data(snt_connect_offers, "title-string", /*titleString*/ ctx[4]);
			}

			if (!current || dirty & /*href*/ 32) {
				set_custom_element_data(snt_connect_offers, "href", /*href*/ ctx[5]);
			}

			if (!current || dirty & /*target*/ 64) {
				set_custom_element_data(snt_connect_offers, "target", /*target*/ ctx[6]);
			}

			if (!current || dirty & /*description*/ 128) {
				set_custom_element_data(snt_connect_offers, "description", /*description*/ ctx[7]);
			}

			if (!current || dirty & /*buttonLabel*/ 256) {
				set_custom_element_data(snt_connect_offers, "button-label", /*buttonLabel*/ ctx[8]);
			}

			if (!current || dirty & /*ariaLabel*/ 512) {
				set_custom_element_data(snt_connect_offers, "aria-label", /*ariaLabel*/ ctx[9]);
			}

			if (!current || dirty & /*actionReference*/ 1024) {
				set_custom_element_data(snt_connect_offers, "action-reference", /*actionReference*/ ctx[10]);
			}

			if (!current || dirty & /*actionData*/ 2048) {
				set_custom_element_data(snt_connect_offers, "action-data", /*actionData*/ ctx[11]);
			}

			if (!current || dirty & /*modalData*/ 4096) {
				set_custom_element_data(snt_connect_offers, "modal-data", /*modalData*/ ctx[12]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_connect_offers);
			if (default_slot) default_slot.d(detaching);
			/*snt_connect_offers_binding*/ ctx[17](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { offerAvailable = undefined } = $$props;
	let { logoSources = undefined } = $$props;
	let { altTag = undefined } = $$props;
	let { offerTitle = undefined } = $$props;
	let { titleString = undefined } = $$props;
	let { href = undefined } = $$props;
	let { target = undefined } = $$props;
	let { description = undefined } = $$props;
	let { buttonLabel = undefined } = $$props;
	let { ariaLabel = undefined } = $$props;
	let { actionReference = undefined } = $$props;
	let { actionData = undefined } = $$props;
	let { modalData = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(13, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_connect_offers_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(13, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("offerAvailable" in $$props) $$invalidate(0, offerAvailable = $$props.offerAvailable);
		if ("logoSources" in $$props) $$invalidate(1, logoSources = $$props.logoSources);
		if ("altTag" in $$props) $$invalidate(2, altTag = $$props.altTag);
		if ("offerTitle" in $$props) $$invalidate(3, offerTitle = $$props.offerTitle);
		if ("titleString" in $$props) $$invalidate(4, titleString = $$props.titleString);
		if ("href" in $$props) $$invalidate(5, href = $$props.href);
		if ("target" in $$props) $$invalidate(6, target = $$props.target);
		if ("description" in $$props) $$invalidate(7, description = $$props.description);
		if ("buttonLabel" in $$props) $$invalidate(8, buttonLabel = $$props.buttonLabel);
		if ("ariaLabel" in $$props) $$invalidate(9, ariaLabel = $$props.ariaLabel);
		if ("actionReference" in $$props) $$invalidate(10, actionReference = $$props.actionReference);
		if ("actionData" in $$props) $$invalidate(11, actionData = $$props.actionData);
		if ("modalData" in $$props) $$invalidate(12, modalData = $$props.modalData);
		if ("$$scope" in $$props) $$invalidate(15, $$scope = $$props.$$scope);
	};

	return [
		offerAvailable,
		logoSources,
		altTag,
		offerTitle,
		titleString,
		href,
		target,
		description,
		buttonLabel,
		ariaLabel,
		actionReference,
		actionData,
		modalData,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_connect_offers_binding
	];
}

class SntConnectOffers extends SvelteComponent {
  $$prop_def: SntConnectOffersProps;
  $$events_def: SntConnectOffersEvents;
  $$slot_def: SntConnectOffersSlots;

  $on<K extends keyof SntConnectOffersEvents>(type: K, callback: (e: SntConnectOffersEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntConnectOffersProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			offerAvailable: 0,
			logoSources: 1,
			altTag: 2,
			offerTitle: 3,
			titleString: 4,
			href: 5,
			target: 6,
			description: 7,
			buttonLabel: 8,
			ariaLabel: 9,
			actionReference: 10,
			actionData: 11,
			modalData: 12,
			getWebComponent: 14
		});
	}

	get getWebComponent(): HTMLSntConnectOffersElement | undefined {
		return this.$$.ctx[14];
	}
}

export default SntConnectOffers;