/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntFaqFilterSliderProps {
  
  /**  */
  filterItems?: Components.SntFaqFilterSlider["filterItems"]
  
  /**  */
  menuAriaLabel?: Components.SntFaqFilterSlider["menuAriaLabel"]
  
  /**  */
  currentActive?: Components.SntFaqFilterSlider["currentActive"]
}

interface SntFaqFilterSliderEvents {
  
  /**  */
  faqFilterClick: Parameters<JSX.SntFaqFilterSlider["onFaqFilterClick"]>[0]
}

interface SntFaqFilterSliderSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_faq_filter_slider;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			snt_faq_filter_slider = element("snt-faq-filter-slider");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_faq_filter_slider, "filter-items", /*filterItems*/ ctx[0]);
			set_custom_element_data(snt_faq_filter_slider, "menu-aria-label", /*menuAriaLabel*/ ctx[1]);
			set_custom_element_data(snt_faq_filter_slider, "current-active", /*currentActive*/ ctx[2]);
		},
		m(target, anchor) {
			insert(target, snt_faq_filter_slider, anchor);

			if (default_slot) {
				default_slot.m(snt_faq_filter_slider, null);
			}

			/*snt_faq_filter_slider_binding*/ ctx[8](snt_faq_filter_slider);
			current = true;

			if (!mounted) {
				dispose = listen(snt_faq_filter_slider, "faqFilterClick", /*onEvent*/ ctx[4]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}

			if (!current || dirty & /*filterItems*/ 1) {
				set_custom_element_data(snt_faq_filter_slider, "filter-items", /*filterItems*/ ctx[0]);
			}

			if (!current || dirty & /*menuAriaLabel*/ 2) {
				set_custom_element_data(snt_faq_filter_slider, "menu-aria-label", /*menuAriaLabel*/ ctx[1]);
			}

			if (!current || dirty & /*currentActive*/ 4) {
				set_custom_element_data(snt_faq_filter_slider, "current-active", /*currentActive*/ ctx[2]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_faq_filter_slider);
			if (default_slot) default_slot.d(detaching);
			/*snt_faq_filter_slider_binding*/ ctx[8](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { filterItems = undefined } = $$props;
	let { menuAriaLabel = undefined } = $$props;
	let { currentActive = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(3, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_faq_filter_slider_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(3, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("filterItems" in $$props) $$invalidate(0, filterItems = $$props.filterItems);
		if ("menuAriaLabel" in $$props) $$invalidate(1, menuAriaLabel = $$props.menuAriaLabel);
		if ("currentActive" in $$props) $$invalidate(2, currentActive = $$props.currentActive);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	return [
		filterItems,
		menuAriaLabel,
		currentActive,
		__ref,
		onEvent,
		getWebComponent,
		$$scope,
		slots,
		snt_faq_filter_slider_binding
	];
}

class SntFaqFilterSlider extends SvelteComponent {
  $$prop_def: SntFaqFilterSliderProps;
  $$events_def: SntFaqFilterSliderEvents;
  $$slot_def: SntFaqFilterSliderSlots;

  $on<K extends keyof SntFaqFilterSliderEvents>(type: K, callback: (e: SntFaqFilterSliderEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntFaqFilterSliderProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			filterItems: 0,
			menuAriaLabel: 1,
			currentActive: 2,
			getWebComponent: 5
		});
	}

	get getWebComponent(): HTMLSntFaqFilterSliderElement | undefined {
		return this.$$.ctx[5];
	}
}

export default SntFaqFilterSlider;