/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntFaqBlockProps {
  
  /**  */
  titleText?: Components.SntFaqBlock["titleText"]
  
  /**  */
  bodyText?: Components.SntFaqBlock["bodyText"]
  
  /**  */
  articlesCount?: Components.SntFaqBlock["articlesCount"]
  
  /**  */
  blockLink?: Components.SntFaqBlock["blockLink"]
}

interface SntFaqBlockEvents {
  
}

interface SntFaqBlockSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_faq_block;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			snt_faq_block = element("snt-faq-block");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_faq_block, "title-text", /*titleText*/ ctx[0]);
			set_custom_element_data(snt_faq_block, "body-text", /*bodyText*/ ctx[1]);
			set_custom_element_data(snt_faq_block, "articles-count", /*articlesCount*/ ctx[2]);
			set_custom_element_data(snt_faq_block, "block-link", /*blockLink*/ ctx[3]);
		},
		m(target, anchor) {
			insert(target, snt_faq_block, anchor);

			if (default_slot) {
				default_slot.m(snt_faq_block, null);
			}

			/*snt_faq_block_binding*/ ctx[8](snt_faq_block);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}

			if (!current || dirty & /*titleText*/ 1) {
				set_custom_element_data(snt_faq_block, "title-text", /*titleText*/ ctx[0]);
			}

			if (!current || dirty & /*bodyText*/ 2) {
				set_custom_element_data(snt_faq_block, "body-text", /*bodyText*/ ctx[1]);
			}

			if (!current || dirty & /*articlesCount*/ 4) {
				set_custom_element_data(snt_faq_block, "articles-count", /*articlesCount*/ ctx[2]);
			}

			if (!current || dirty & /*blockLink*/ 8) {
				set_custom_element_data(snt_faq_block, "block-link", /*blockLink*/ ctx[3]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_faq_block);
			if (default_slot) default_slot.d(detaching);
			/*snt_faq_block_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { titleText = undefined } = $$props;
	let { bodyText = undefined } = $$props;
	let { articlesCount = undefined } = $$props;
	let { blockLink = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(4, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_faq_block_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(4, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("titleText" in $$props) $$invalidate(0, titleText = $$props.titleText);
		if ("bodyText" in $$props) $$invalidate(1, bodyText = $$props.bodyText);
		if ("articlesCount" in $$props) $$invalidate(2, articlesCount = $$props.articlesCount);
		if ("blockLink" in $$props) $$invalidate(3, blockLink = $$props.blockLink);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	return [
		titleText,
		bodyText,
		articlesCount,
		blockLink,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_faq_block_binding
	];
}

class SntFaqBlock extends SvelteComponent {
  $$prop_def: SntFaqBlockProps;
  $$events_def: SntFaqBlockEvents;
  $$slot_def: SntFaqBlockSlots;

  $on<K extends keyof SntFaqBlockEvents>(type: K, callback: (e: SntFaqBlockEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntFaqBlockProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			titleText: 0,
			bodyText: 1,
			articlesCount: 2,
			blockLink: 3,
			getWebComponent: 5
		});
	}

	get getWebComponent(): HTMLSntFaqBlockElement | undefined {
		return this.$$.ctx[5];
	}
}

export default SntFaqBlock;