/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntFaqBlockListProps {
  
  /**  */
  faqBlockList?: Components.SntFaqBlockList["faqBlockList"]
  
  /**  */
  menuAriaLabel?: Components.SntFaqBlockList["menuAriaLabel"]
}

interface SntFaqBlockListEvents {
  
}

interface SntFaqBlockListSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_faq_block_list;
	let current;
	const default_slot_template = /*#slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			snt_faq_block_list = element("snt-faq-block-list");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_faq_block_list, "menu-aria-label", /*menuAriaLabel*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, snt_faq_block_list, anchor);

			if (default_slot) {
				default_slot.m(snt_faq_block_list, null);
			}

			/*snt_faq_block_list_binding*/ ctx[7](snt_faq_block_list);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 32) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[5], dirty, null, null);
				}
			}

			if (!current || dirty & /*menuAriaLabel*/ 1) {
				set_custom_element_data(snt_faq_block_list, "menu-aria-label", /*menuAriaLabel*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_faq_block_list);
			if (default_slot) default_slot.d(detaching);
			/*snt_faq_block_list_binding*/ ctx[7](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { faqBlockList = undefined } = $$props;
	let { menuAriaLabel = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(4, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_faq_block_list_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("faqBlockList" in $$props) $$invalidate(2, faqBlockList = $$props.faqBlockList);
		if ("menuAriaLabel" in $$props) $$invalidate(0, menuAriaLabel = $$props.menuAriaLabel);
		if ("$$scope" in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, faqBlockList*/ 20) {
			$: if (__mounted) setProp("faqBlockList", faqBlockList);
		}
	};

	return [
		menuAriaLabel,
		__ref,
		faqBlockList,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		snt_faq_block_list_binding
	];
}

class SntFaqBlockList extends SvelteComponent {
  $$prop_def: SntFaqBlockListProps;
  $$events_def: SntFaqBlockListEvents;
  $$slot_def: SntFaqBlockListSlots;

  $on<K extends keyof SntFaqBlockListEvents>(type: K, callback: (e: SntFaqBlockListEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntFaqBlockListProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			faqBlockList: 2,
			menuAriaLabel: 0,
			getWebComponent: 3
		});
	}

	get getWebComponent(): HTMLSntFaqBlockListElement | undefined {
		return this.$$.ctx[3];
	}
}

export default SntFaqBlockList;