/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntHeroProps {
  
  /**  */
  propertiesSrc?: Components.SntHero["propertiesSrc"]
  
  /**  */
  properties?: Components.SntHero["properties"]
}

interface SntHeroEvents {
  
}

interface SntHeroSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_hero;
	let current;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			snt_hero = element("snt-hero");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_hero, "properties-src", /*propertiesSrc*/ ctx[0]);
			set_custom_element_data(snt_hero, "properties", /*properties*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, snt_hero, anchor);

			if (default_slot) {
				default_slot.m(snt_hero, null);
			}

			/*snt_hero_binding*/ ctx[6](snt_hero);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 16) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[4], dirty, null, null);
				}
			}

			if (!current || dirty & /*propertiesSrc*/ 1) {
				set_custom_element_data(snt_hero, "properties-src", /*propertiesSrc*/ ctx[0]);
			}

			if (!current || dirty & /*properties*/ 2) {
				set_custom_element_data(snt_hero, "properties", /*properties*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_hero);
			if (default_slot) default_slot.d(detaching);
			/*snt_hero_binding*/ ctx[6](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { propertiesSrc = undefined } = $$props;
	let { properties = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_hero_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("propertiesSrc" in $$props) $$invalidate(0, propertiesSrc = $$props.propertiesSrc);
		if ("properties" in $$props) $$invalidate(1, properties = $$props.properties);
		if ("$$scope" in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	return [
		propertiesSrc,
		properties,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_hero_binding
	];
}

class SntHero extends SvelteComponent {
  $$prop_def: SntHeroProps;
  $$events_def: SntHeroEvents;
  $$slot_def: SntHeroSlots;

  $on<K extends keyof SntHeroEvents>(type: K, callback: (e: SntHeroEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntHeroProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			propertiesSrc: 0,
			properties: 1,
			getWebComponent: 3
		});
	}

	get getWebComponent(): HTMLSntHeroElement | undefined {
		return this.$$.ctx[3];
	}
}

export default SntHero;