/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntHeaderProps {
  
  /**  */
  styleClasses?: Components.SntHeader["styleClasses"]
  
  /**  */
  fixed?: Components.SntHeader["fixed"]
  
  /**  */
  languageJson?: Components.SntHeader["languageJson"]
  
  /**  */
  mainContentId?: Components.SntHeader["mainContentId"]
  
  /**  */
  active?: Components.SntHeader["active"]
}

interface SntHeaderEvents {
  
}

interface SntHeaderSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_header;
	let current;
	const default_slot_template = /*#slots*/ ctx[10].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[9], null);

	return {
		c() {
			snt_header = element("snt-header");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_header, "style-classes", /*styleClasses*/ ctx[0]);
			set_custom_element_data(snt_header, "fixed", /*fixed*/ ctx[1]);
			set_custom_element_data(snt_header, "language-json", /*languageJson*/ ctx[2]);
			set_custom_element_data(snt_header, "main-content-id", /*mainContentId*/ ctx[3]);
			set_custom_element_data(snt_header, "active", /*active*/ ctx[4]);
		},
		m(target, anchor) {
			insert(target, snt_header, anchor);

			if (default_slot) {
				default_slot.m(snt_header, null);
			}

			/*snt_header_binding*/ ctx[11](snt_header);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 512) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[9], dirty, null, null);
				}
			}

			if (!current || dirty & /*styleClasses*/ 1) {
				set_custom_element_data(snt_header, "style-classes", /*styleClasses*/ ctx[0]);
			}

			if (!current || dirty & /*fixed*/ 2) {
				set_custom_element_data(snt_header, "fixed", /*fixed*/ ctx[1]);
			}

			if (!current || dirty & /*languageJson*/ 4) {
				set_custom_element_data(snt_header, "language-json", /*languageJson*/ ctx[2]);
			}

			if (!current || dirty & /*mainContentId*/ 8) {
				set_custom_element_data(snt_header, "main-content-id", /*mainContentId*/ ctx[3]);
			}

			if (!current || dirty & /*active*/ 16) {
				set_custom_element_data(snt_header, "active", /*active*/ ctx[4]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_header);
			if (default_slot) default_slot.d(detaching);
			/*snt_header_binding*/ ctx[11](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { styleClasses = undefined } = $$props;
	let { fixed = undefined } = $$props;
	let { languageJson = undefined } = $$props;
	let { mainContentId = undefined } = $$props;
	let { active = undefined } = $$props;
	const toggleActive = (...args) => __ref.toggleActive(...args);
	const setActive = (...args) => __ref.setActive(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(5, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_header_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(5, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("styleClasses" in $$props) $$invalidate(0, styleClasses = $$props.styleClasses);
		if ("fixed" in $$props) $$invalidate(1, fixed = $$props.fixed);
		if ("languageJson" in $$props) $$invalidate(2, languageJson = $$props.languageJson);
		if ("mainContentId" in $$props) $$invalidate(3, mainContentId = $$props.mainContentId);
		if ("active" in $$props) $$invalidate(4, active = $$props.active);
		if ("$$scope" in $$props) $$invalidate(9, $$scope = $$props.$$scope);
	};

	return [
		styleClasses,
		fixed,
		languageJson,
		mainContentId,
		active,
		__ref,
		toggleActive,
		setActive,
		getWebComponent,
		$$scope,
		slots,
		snt_header_binding
	];
}

class SntHeader extends SvelteComponent {
  $$prop_def: SntHeaderProps;
  $$events_def: SntHeaderEvents;
  $$slot_def: SntHeaderSlots;

  $on<K extends keyof SntHeaderEvents>(type: K, callback: (e: SntHeaderEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntHeaderProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			styleClasses: 0,
			fixed: 1,
			languageJson: 2,
			mainContentId: 3,
			active: 4,
			toggleActive: 6,
			setActive: 7,
			getWebComponent: 8
		});
	}

	
  /**  */
 get toggleActive(): Components.SntHeader["toggleActive"] {
		return this.$$.ctx[6];
	}

	
  /**  */
 get setActive(): Components.SntHeader["setActive"] {
		return this.$$.ctx[7];
	}

	get getWebComponent(): HTMLSntHeaderElement | undefined {
		return this.$$.ctx[8];
	}
}

export default SntHeader;