/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntImageColumnProps {
  
  /**  */
  imageSrc?: Components.SntImageColumn["imageSrc"]
  
  /**  */
  imgAlt?: Components.SntImageColumn["imgAlt"]
}

interface SntImageColumnEvents {
  
}

interface SntImageColumnSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_image_column;
	let current;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			snt_image_column = element("snt-image-column");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_image_column, "image-src", /*imageSrc*/ ctx[0]);
			set_custom_element_data(snt_image_column, "img-alt", /*imgAlt*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, snt_image_column, anchor);

			if (default_slot) {
				default_slot.m(snt_image_column, null);
			}

			/*snt_image_column_binding*/ ctx[6](snt_image_column);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 16) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[4], dirty, null, null);
				}
			}

			if (!current || dirty & /*imageSrc*/ 1) {
				set_custom_element_data(snt_image_column, "image-src", /*imageSrc*/ ctx[0]);
			}

			if (!current || dirty & /*imgAlt*/ 2) {
				set_custom_element_data(snt_image_column, "img-alt", /*imgAlt*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_image_column);
			if (default_slot) default_slot.d(detaching);
			/*snt_image_column_binding*/ ctx[6](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { imageSrc = undefined } = $$props;
	let { imgAlt = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_image_column_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("imageSrc" in $$props) $$invalidate(0, imageSrc = $$props.imageSrc);
		if ("imgAlt" in $$props) $$invalidate(1, imgAlt = $$props.imgAlt);
		if ("$$scope" in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	return [
		imageSrc,
		imgAlt,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_image_column_binding
	];
}

class SntImageColumn extends SvelteComponent {
  $$prop_def: SntImageColumnProps;
  $$events_def: SntImageColumnEvents;
  $$slot_def: SntImageColumnSlots;

  $on<K extends keyof SntImageColumnEvents>(type: K, callback: (e: SntImageColumnEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntImageColumnProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			imageSrc: 0,
			imgAlt: 1,
			getWebComponent: 3
		});
	}

	get getWebComponent(): HTMLSntImageColumnElement | undefined {
		return this.$$.ctx[3];
	}
}

export default SntImageColumn;