/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntImageIconProps {
  
  /**  */
  properties?: Components.SntImageIcon["properties"]
  
  /**  */
  imgAlt?: Components.SntImageIcon["imgAlt"]
  
  /**  */
  styleClasses?: Components.SntImageIcon["styleClasses"]
}

interface SntImageIconEvents {
  
}

interface SntImageIconSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_image_icon;
	let current;
	const default_slot_template = /*#slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			snt_image_icon = element("snt-image-icon");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_image_icon, "properties", /*properties*/ ctx[0]);
			set_custom_element_data(snt_image_icon, "img-alt", /*imgAlt*/ ctx[1]);
			set_custom_element_data(snt_image_icon, "style-classes", /*styleClasses*/ ctx[2]);
		},
		m(target, anchor) {
			insert(target, snt_image_icon, anchor);

			if (default_slot) {
				default_slot.m(snt_image_icon, null);
			}

			/*snt_image_icon_binding*/ ctx[7](snt_image_icon);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 32) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[5], dirty, null, null);
				}
			}

			if (!current || dirty & /*properties*/ 1) {
				set_custom_element_data(snt_image_icon, "properties", /*properties*/ ctx[0]);
			}

			if (!current || dirty & /*imgAlt*/ 2) {
				set_custom_element_data(snt_image_icon, "img-alt", /*imgAlt*/ ctx[1]);
			}

			if (!current || dirty & /*styleClasses*/ 4) {
				set_custom_element_data(snt_image_icon, "style-classes", /*styleClasses*/ ctx[2]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_image_icon);
			if (default_slot) default_slot.d(detaching);
			/*snt_image_icon_binding*/ ctx[7](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { properties = undefined } = $$props;
	let { imgAlt = undefined } = $$props;
	let { styleClasses = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(3, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_image_icon_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(3, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("properties" in $$props) $$invalidate(0, properties = $$props.properties);
		if ("imgAlt" in $$props) $$invalidate(1, imgAlt = $$props.imgAlt);
		if ("styleClasses" in $$props) $$invalidate(2, styleClasses = $$props.styleClasses);
		if ("$$scope" in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	return [
		properties,
		imgAlt,
		styleClasses,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_image_icon_binding
	];
}

class SntImageIcon extends SvelteComponent {
  $$prop_def: SntImageIconProps;
  $$events_def: SntImageIconEvents;
  $$slot_def: SntImageIconSlots;

  $on<K extends keyof SntImageIconEvents>(type: K, callback: (e: SntImageIconEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntImageIconProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			properties: 0,
			imgAlt: 1,
			styleClasses: 2,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLSntImageIconElement | undefined {
		return this.$$.ctx[4];
	}
}

export default SntImageIcon;