/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntLayoutProps {
  
  /**  */
  viewport?: Components.SntLayout["viewport"]
  
  /**  */
  padding?: Components.SntLayout["padding"]
}

interface SntLayoutEvents {
  
  /**  */
  viewportChanged: Parameters<JSX.SntLayout["onViewportChanged"]>[0]
}

interface SntLayoutSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_layout;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			snt_layout = element("snt-layout");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_layout, "viewport", /*viewport*/ ctx[0]);
			set_custom_element_data(snt_layout, "padding", /*padding*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, snt_layout, anchor);

			if (default_slot) {
				default_slot.m(snt_layout, null);
			}

			/*snt_layout_binding*/ ctx[7](snt_layout);
			current = true;

			if (!mounted) {
				dispose = listen(snt_layout, "viewportChanged", /*onEvent*/ ctx[3]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 32) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[5], dirty, null, null);
				}
			}

			if (!current || dirty & /*viewport*/ 1) {
				set_custom_element_data(snt_layout, "viewport", /*viewport*/ ctx[0]);
			}

			if (!current || dirty & /*padding*/ 2) {
				set_custom_element_data(snt_layout, "padding", /*padding*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_layout);
			if (default_slot) default_slot.d(detaching);
			/*snt_layout_binding*/ ctx[7](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { viewport = undefined } = $$props;
	let { padding = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_layout_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("viewport" in $$props) $$invalidate(0, viewport = $$props.viewport);
		if ("padding" in $$props) $$invalidate(1, padding = $$props.padding);
		if ("$$scope" in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	return [
		viewport,
		padding,
		__ref,
		onEvent,
		getWebComponent,
		$$scope,
		slots,
		snt_layout_binding
	];
}

class SntLayout extends SvelteComponent {
  $$prop_def: SntLayoutProps;
  $$events_def: SntLayoutEvents;
  $$slot_def: SntLayoutSlots;

  $on<K extends keyof SntLayoutEvents>(type: K, callback: (e: SntLayoutEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntLayoutProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			viewport: 0,
			padding: 1,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLSntLayoutElement | undefined {
		return this.$$.ctx[4];
	}
}

export default SntLayout;