/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntLoginProps {
  
  /**  */
  authed?: Components.SntLogin["authed"]
  
  /**  */
  languageJson?: Components.SntLogin["languageJson"]
  
  /**  */
  accountLoginUrl?: Components.SntLogin["accountLoginUrl"]
  
  /**  */
  accountDashboardUrl?: Components.SntLogin["accountDashboardUrl"]
}

interface SntLoginEvents {
  
}

interface SntLoginSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_login;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			snt_login = element("snt-login");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_login, "authed", /*authed*/ ctx[0]);
			set_custom_element_data(snt_login, "language-json", /*languageJson*/ ctx[1]);
			set_custom_element_data(snt_login, "account-login-url", /*accountLoginUrl*/ ctx[2]);
			set_custom_element_data(snt_login, "account-dashboard-url", /*accountDashboardUrl*/ ctx[3]);
		},
		m(target, anchor) {
			insert(target, snt_login, anchor);

			if (default_slot) {
				default_slot.m(snt_login, null);
			}

			/*snt_login_binding*/ ctx[8](snt_login);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}

			if (!current || dirty & /*authed*/ 1) {
				set_custom_element_data(snt_login, "authed", /*authed*/ ctx[0]);
			}

			if (!current || dirty & /*languageJson*/ 2) {
				set_custom_element_data(snt_login, "language-json", /*languageJson*/ ctx[1]);
			}

			if (!current || dirty & /*accountLoginUrl*/ 4) {
				set_custom_element_data(snt_login, "account-login-url", /*accountLoginUrl*/ ctx[2]);
			}

			if (!current || dirty & /*accountDashboardUrl*/ 8) {
				set_custom_element_data(snt_login, "account-dashboard-url", /*accountDashboardUrl*/ ctx[3]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_login);
			if (default_slot) default_slot.d(detaching);
			/*snt_login_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { authed = undefined } = $$props;
	let { languageJson = undefined } = $$props;
	let { accountLoginUrl = undefined } = $$props;
	let { accountDashboardUrl = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(4, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_login_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(4, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("authed" in $$props) $$invalidate(0, authed = $$props.authed);
		if ("languageJson" in $$props) $$invalidate(1, languageJson = $$props.languageJson);
		if ("accountLoginUrl" in $$props) $$invalidate(2, accountLoginUrl = $$props.accountLoginUrl);
		if ("accountDashboardUrl" in $$props) $$invalidate(3, accountDashboardUrl = $$props.accountDashboardUrl);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	return [
		authed,
		languageJson,
		accountLoginUrl,
		accountDashboardUrl,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_login_binding
	];
}

class SntLogin extends SvelteComponent {
  $$prop_def: SntLoginProps;
  $$events_def: SntLoginEvents;
  $$slot_def: SntLoginSlots;

  $on<K extends keyof SntLoginEvents>(type: K, callback: (e: SntLoginEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntLoginProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			authed: 0,
			languageJson: 1,
			accountLoginUrl: 2,
			accountDashboardUrl: 3,
			getWebComponent: 5
		});
	}

	get getWebComponent(): HTMLSntLoginElement | undefined {
		return this.$$.ctx[5];
	}
}

export default SntLogin;