/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntNavbarToggleProps {
  
  /**  */
  collapsed?: Components.SntNavbarToggle["collapsed"]
  
  /**  */
  ariaControls?: Components.SntNavbarToggle["ariaControls"]
  
  /**  */
  languageString?: Components.SntNavbarToggle["languageString"]
}

interface SntNavbarToggleEvents {
  
  /**  */
  navbarToggled: Parameters<JSX.SntNavbarToggle["onNavbarToggled"]>[0]
}

interface SntNavbarToggleSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_navbar_toggle;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[8].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[7], null);

	return {
		c() {
			snt_navbar_toggle = element("snt-navbar-toggle");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_navbar_toggle, "collapsed", /*collapsed*/ ctx[0]);
			set_custom_element_data(snt_navbar_toggle, "aria-controls", /*ariaControls*/ ctx[1]);
			set_custom_element_data(snt_navbar_toggle, "language-string", /*languageString*/ ctx[2]);
		},
		m(target, anchor) {
			insert(target, snt_navbar_toggle, anchor);

			if (default_slot) {
				default_slot.m(snt_navbar_toggle, null);
			}

			/*snt_navbar_toggle_binding*/ ctx[9](snt_navbar_toggle);
			current = true;

			if (!mounted) {
				dispose = listen(snt_navbar_toggle, "navbarToggled", /*onEvent*/ ctx[4]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 128) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[7], dirty, null, null);
				}
			}

			if (!current || dirty & /*collapsed*/ 1) {
				set_custom_element_data(snt_navbar_toggle, "collapsed", /*collapsed*/ ctx[0]);
			}

			if (!current || dirty & /*ariaControls*/ 2) {
				set_custom_element_data(snt_navbar_toggle, "aria-controls", /*ariaControls*/ ctx[1]);
			}

			if (!current || dirty & /*languageString*/ 4) {
				set_custom_element_data(snt_navbar_toggle, "language-string", /*languageString*/ ctx[2]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_navbar_toggle);
			if (default_slot) default_slot.d(detaching);
			/*snt_navbar_toggle_binding*/ ctx[9](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { collapsed = undefined } = $$props;
	let { ariaControls = undefined } = $$props;
	let { languageString = undefined } = $$props;
	const toggleCollapsed = (...args) => __ref.toggleCollapsed(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(3, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_navbar_toggle_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(3, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("collapsed" in $$props) $$invalidate(0, collapsed = $$props.collapsed);
		if ("ariaControls" in $$props) $$invalidate(1, ariaControls = $$props.ariaControls);
		if ("languageString" in $$props) $$invalidate(2, languageString = $$props.languageString);
		if ("$$scope" in $$props) $$invalidate(7, $$scope = $$props.$$scope);
	};

	return [
		collapsed,
		ariaControls,
		languageString,
		__ref,
		onEvent,
		toggleCollapsed,
		getWebComponent,
		$$scope,
		slots,
		snt_navbar_toggle_binding
	];
}

class SntNavbarToggle extends SvelteComponent {
  $$prop_def: SntNavbarToggleProps;
  $$events_def: SntNavbarToggleEvents;
  $$slot_def: SntNavbarToggleSlots;

  $on<K extends keyof SntNavbarToggleEvents>(type: K, callback: (e: SntNavbarToggleEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntNavbarToggleProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			collapsed: 0,
			ariaControls: 1,
			languageString: 2,
			toggleCollapsed: 5,
			getWebComponent: 6
		});
	}

	
  /**  */
 get toggleCollapsed(): Components.SntNavbarToggle["toggleCollapsed"] {
		return this.$$.ctx[5];
	}

	get getWebComponent(): HTMLSntNavbarToggleElement | undefined {
		return this.$$.ctx[6];
	}
}

export default SntNavbarToggle;