/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntNavbarCollapseProps {
  
  /**  */
  shown?: Components.SntNavbarCollapse["shown"]
  
  /**  */
  viewport?: Components.SntNavbarCollapse["viewport"]
  
  /**  */
  logoUrl?: Components.SntNavbarCollapse["logoUrl"]
}

interface SntNavbarCollapseEvents {
  
  /**  */
  navbarToggled: Parameters<JSX.SntNavbarCollapse["onNavbarToggled"]>[0]
}

interface SntNavbarCollapseSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_navbar_collapse;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[8].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[7], null);

	return {
		c() {
			snt_navbar_collapse = element("snt-navbar-collapse");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_navbar_collapse, "shown", /*shown*/ ctx[0]);
			set_custom_element_data(snt_navbar_collapse, "viewport", /*viewport*/ ctx[1]);
			set_custom_element_data(snt_navbar_collapse, "logo-url", /*logoUrl*/ ctx[2]);
		},
		m(target, anchor) {
			insert(target, snt_navbar_collapse, anchor);

			if (default_slot) {
				default_slot.m(snt_navbar_collapse, null);
			}

			/*snt_navbar_collapse_binding*/ ctx[9](snt_navbar_collapse);
			current = true;

			if (!mounted) {
				dispose = listen(snt_navbar_collapse, "navbarToggled", /*onEvent*/ ctx[4]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 128) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[7], dirty, null, null);
				}
			}

			if (!current || dirty & /*shown*/ 1) {
				set_custom_element_data(snt_navbar_collapse, "shown", /*shown*/ ctx[0]);
			}

			if (!current || dirty & /*viewport*/ 2) {
				set_custom_element_data(snt_navbar_collapse, "viewport", /*viewport*/ ctx[1]);
			}

			if (!current || dirty & /*logoUrl*/ 4) {
				set_custom_element_data(snt_navbar_collapse, "logo-url", /*logoUrl*/ ctx[2]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_navbar_collapse);
			if (default_slot) default_slot.d(detaching);
			/*snt_navbar_collapse_binding*/ ctx[9](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { shown = undefined } = $$props;
	let { viewport = undefined } = $$props;
	let { logoUrl = undefined } = $$props;
	const toggleShown = (...args) => __ref.toggleShown(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(3, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_navbar_collapse_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(3, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("shown" in $$props) $$invalidate(0, shown = $$props.shown);
		if ("viewport" in $$props) $$invalidate(1, viewport = $$props.viewport);
		if ("logoUrl" in $$props) $$invalidate(2, logoUrl = $$props.logoUrl);
		if ("$$scope" in $$props) $$invalidate(7, $$scope = $$props.$$scope);
	};

	return [
		shown,
		viewport,
		logoUrl,
		__ref,
		onEvent,
		toggleShown,
		getWebComponent,
		$$scope,
		slots,
		snt_navbar_collapse_binding
	];
}

class SntNavbarCollapse extends SvelteComponent {
  $$prop_def: SntNavbarCollapseProps;
  $$events_def: SntNavbarCollapseEvents;
  $$slot_def: SntNavbarCollapseSlots;

  $on<K extends keyof SntNavbarCollapseEvents>(type: K, callback: (e: SntNavbarCollapseEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntNavbarCollapseProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			shown: 0,
			viewport: 1,
			logoUrl: 2,
			toggleShown: 5,
			getWebComponent: 6
		});
	}

	
  /**  */
 get toggleShown(): Components.SntNavbarCollapse["toggleShown"] {
		return this.$$.ctx[5];
	}

	get getWebComponent(): HTMLSntNavbarCollapseElement | undefined {
		return this.$$.ctx[6];
	}
}

export default SntNavbarCollapse;