/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntNavbarProps {
  
  /**  */
  styleClasses?: Components.SntNavbar["styleClasses"]
  
  /**  */
  active?: Components.SntNavbar["active"]
  
  /**  */
  viewport?: Components.SntNavbar["viewport"]
  
  /**  */
  languageString?: Components.SntNavbar["languageString"]
}

interface SntNavbarEvents {
  
}

interface SntNavbarSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_navbar;
	let current;
	const default_slot_template = /*#slots*/ ctx[8].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[7], null);

	return {
		c() {
			snt_navbar = element("snt-navbar");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_navbar, "style-classes", /*styleClasses*/ ctx[0]);
			set_custom_element_data(snt_navbar, "active", /*active*/ ctx[1]);
			set_custom_element_data(snt_navbar, "viewport", /*viewport*/ ctx[2]);
			set_custom_element_data(snt_navbar, "language-string", /*languageString*/ ctx[3]);
		},
		m(target, anchor) {
			insert(target, snt_navbar, anchor);

			if (default_slot) {
				default_slot.m(snt_navbar, null);
			}

			/*snt_navbar_binding*/ ctx[9](snt_navbar);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 128) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[7], dirty, null, null);
				}
			}

			if (!current || dirty & /*styleClasses*/ 1) {
				set_custom_element_data(snt_navbar, "style-classes", /*styleClasses*/ ctx[0]);
			}

			if (!current || dirty & /*active*/ 2) {
				set_custom_element_data(snt_navbar, "active", /*active*/ ctx[1]);
			}

			if (!current || dirty & /*viewport*/ 4) {
				set_custom_element_data(snt_navbar, "viewport", /*viewport*/ ctx[2]);
			}

			if (!current || dirty & /*languageString*/ 8) {
				set_custom_element_data(snt_navbar, "language-string", /*languageString*/ ctx[3]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_navbar);
			if (default_slot) default_slot.d(detaching);
			/*snt_navbar_binding*/ ctx[9](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { styleClasses = undefined } = $$props;
	let { active = undefined } = $$props;
	let { viewport = undefined } = $$props;
	let { languageString = undefined } = $$props;
	const toggleActive = (...args) => __ref.toggleActive(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(4, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_navbar_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(4, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("styleClasses" in $$props) $$invalidate(0, styleClasses = $$props.styleClasses);
		if ("active" in $$props) $$invalidate(1, active = $$props.active);
		if ("viewport" in $$props) $$invalidate(2, viewport = $$props.viewport);
		if ("languageString" in $$props) $$invalidate(3, languageString = $$props.languageString);
		if ("$$scope" in $$props) $$invalidate(7, $$scope = $$props.$$scope);
	};

	return [
		styleClasses,
		active,
		viewport,
		languageString,
		__ref,
		toggleActive,
		getWebComponent,
		$$scope,
		slots,
		snt_navbar_binding
	];
}

class SntNavbar extends SvelteComponent {
  $$prop_def: SntNavbarProps;
  $$events_def: SntNavbarEvents;
  $$slot_def: SntNavbarSlots;

  $on<K extends keyof SntNavbarEvents>(type: K, callback: (e: SntNavbarEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntNavbarProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			styleClasses: 0,
			active: 1,
			viewport: 2,
			languageString: 3,
			toggleActive: 5,
			getWebComponent: 6
		});
	}

	
  /**  */
 get toggleActive(): Components.SntNavbar["toggleActive"] {
		return this.$$.ctx[5];
	}

	get getWebComponent(): HTMLSntNavbarElement | undefined {
		return this.$$.ctx[6];
	}
}

export default SntNavbar;