/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntRecaptchaProps {
  
  /**  */
  sitekey?: Components.SntRecaptcha["sitekey"]
  
  /**  */
  language?: Components.SntRecaptcha["language"]
}

interface SntRecaptchaEvents {
  
  /**  */
  grecaptchaLoaded: Parameters<JSX.SntRecaptcha["onGrecaptchaLoaded"]>[0]
}

interface SntRecaptchaSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_recaptcha;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			snt_recaptcha = element("snt-recaptcha");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_recaptcha, "sitekey", /*sitekey*/ ctx[0]);
			set_custom_element_data(snt_recaptcha, "language", /*language*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, snt_recaptcha, anchor);

			if (default_slot) {
				default_slot.m(snt_recaptcha, null);
			}

			/*snt_recaptcha_binding*/ ctx[8](snt_recaptcha);
			current = true;

			if (!mounted) {
				dispose = listen(snt_recaptcha, "grecaptchaLoaded", /*onEvent*/ ctx[3]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}

			if (!current || dirty & /*sitekey*/ 1) {
				set_custom_element_data(snt_recaptcha, "sitekey", /*sitekey*/ ctx[0]);
			}

			if (!current || dirty & /*language*/ 2) {
				set_custom_element_data(snt_recaptcha, "language", /*language*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_recaptcha);
			if (default_slot) default_slot.d(detaching);
			/*snt_recaptcha_binding*/ ctx[8](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { sitekey = undefined } = $$props;
	let { language = undefined } = $$props;
	const reset = (...args) => __ref.reset(...args);
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_recaptcha_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("sitekey" in $$props) $$invalidate(0, sitekey = $$props.sitekey);
		if ("language" in $$props) $$invalidate(1, language = $$props.language);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	return [
		sitekey,
		language,
		__ref,
		onEvent,
		reset,
		getWebComponent,
		$$scope,
		slots,
		snt_recaptcha_binding
	];
}

class SntRecaptcha extends SvelteComponent {
  $$prop_def: SntRecaptchaProps;
  $$events_def: SntRecaptchaEvents;
  $$slot_def: SntRecaptchaSlots;

  $on<K extends keyof SntRecaptchaEvents>(type: K, callback: (e: SntRecaptchaEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntRecaptchaProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			sitekey: 0,
			language: 1,
			reset: 4,
			getWebComponent: 5
		});
	}

	
  /**  */
 get reset(): Components.SntRecaptcha["reset"] {
		return this.$$.ctx[4];
	}

	get getWebComponent(): HTMLSntRecaptchaElement | undefined {
		return this.$$.ctx[5];
	}
}

export default SntRecaptcha;