/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntSourceListProps {
  
  /**  */
  panelId?: Components.SntSourceList["panelId"]
  
  /**  */
  sourceHeading?: Components.SntSourceList["sourceHeading"]
}

interface SntSourceListEvents {
  
}

interface SntSourceListSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_source_list;
	let current;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			snt_source_list = element("snt-source-list");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_source_list, "panel-id", /*panelId*/ ctx[0]);
			set_custom_element_data(snt_source_list, "source-heading", /*sourceHeading*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, snt_source_list, anchor);

			if (default_slot) {
				default_slot.m(snt_source_list, null);
			}

			/*snt_source_list_binding*/ ctx[6](snt_source_list);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 16) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[4], dirty, null, null);
				}
			}

			if (!current || dirty & /*panelId*/ 1) {
				set_custom_element_data(snt_source_list, "panel-id", /*panelId*/ ctx[0]);
			}

			if (!current || dirty & /*sourceHeading*/ 2) {
				set_custom_element_data(snt_source_list, "source-heading", /*sourceHeading*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_source_list);
			if (default_slot) default_slot.d(detaching);
			/*snt_source_list_binding*/ ctx[6](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { panelId = undefined } = $$props;
	let { sourceHeading = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_source_list_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("panelId" in $$props) $$invalidate(0, panelId = $$props.panelId);
		if ("sourceHeading" in $$props) $$invalidate(1, sourceHeading = $$props.sourceHeading);
		if ("$$scope" in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	return [
		panelId,
		sourceHeading,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_source_list_binding
	];
}

class SntSourceList extends SvelteComponent {
  $$prop_def: SntSourceListProps;
  $$events_def: SntSourceListEvents;
  $$slot_def: SntSourceListSlots;

  $on<K extends keyof SntSourceListEvents>(type: K, callback: (e: SntSourceListEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntSourceListProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			panelId: 0,
			sourceHeading: 1,
			getWebComponent: 3
		});
	}

	get getWebComponent(): HTMLSntSourceListElement | undefined {
		return this.$$.ctx[3];
	}
}

export default SntSourceList;