/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntTitleCopyProps {
  
  /**  */
  titleString?: Components.SntTitleCopy["titleString"]
  
  /**  */
  styleClasses?: Components.SntTitleCopy["styleClasses"]
}

interface SntTitleCopyEvents {
  
}

interface SntTitleCopySlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_title_copy;
	let current;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			snt_title_copy = element("snt-title-copy");
			if (default_slot) default_slot.c();
			set_custom_element_data(snt_title_copy, "title-string", /*titleString*/ ctx[0]);
			set_custom_element_data(snt_title_copy, "style-classes", /*styleClasses*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, snt_title_copy, anchor);

			if (default_slot) {
				default_slot.m(snt_title_copy, null);
			}

			/*snt_title_copy_binding*/ ctx[6](snt_title_copy);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 16) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[4], dirty, null, null);
				}
			}

			if (!current || dirty & /*titleString*/ 1) {
				set_custom_element_data(snt_title_copy, "title-string", /*titleString*/ ctx[0]);
			}

			if (!current || dirty & /*styleClasses*/ 2) {
				set_custom_element_data(snt_title_copy, "style-classes", /*styleClasses*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_title_copy);
			if (default_slot) default_slot.d(detaching);
			/*snt_title_copy_binding*/ ctx[6](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { titleString = undefined } = $$props;
	let { styleClasses = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_title_copy_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("titleString" in $$props) $$invalidate(0, titleString = $$props.titleString);
		if ("styleClasses" in $$props) $$invalidate(1, styleClasses = $$props.styleClasses);
		if ("$$scope" in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	return [
		titleString,
		styleClasses,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		snt_title_copy_binding
	];
}

class SntTitleCopy extends SvelteComponent {
  $$prop_def: SntTitleCopyProps;
  $$events_def: SntTitleCopyEvents;
  $$slot_def: SntTitleCopySlots;

  $on<K extends keyof SntTitleCopyEvents>(type: K, callback: (e: SntTitleCopyEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntTitleCopyProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			titleString: 0,
			styleClasses: 1,
			getWebComponent: 3
		});
	}

	get getWebComponent(): HTMLSntTitleCopyElement | undefined {
		return this.$$.ctx[3];
	}
}

export default SntTitleCopy;