/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface SntVerticalTabsProps {
  
}

interface SntVerticalTabsEvents {
  
}

interface SntVerticalTabsSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let snt_vertical_tabs;
	let current;
	const default_slot_template = /*#slots*/ ctx[3].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[2], null);

	return {
		c() {
			snt_vertical_tabs = element("snt-vertical-tabs");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, snt_vertical_tabs, anchor);

			if (default_slot) {
				default_slot.m(snt_vertical_tabs, null);
			}

			/*snt_vertical_tabs_binding*/ ctx[4](snt_vertical_tabs);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 4) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[2], dirty, null, null);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(snt_vertical_tabs);
			if (default_slot) default_slot.d(detaching);
			/*snt_vertical_tabs_binding*/ ctx[4](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function snt_vertical_tabs_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("$$scope" in $$props) $$invalidate(2, $$scope = $$props.$$scope);
	};

	return [__ref, getWebComponent, $$scope, slots, snt_vertical_tabs_binding];
}

class SntVerticalTabs extends SvelteComponent {
  $$prop_def: SntVerticalTabsProps;
  $$events_def: SntVerticalTabsEvents;
  $$slot_def: SntVerticalTabsSlots;

  $on<K extends keyof SntVerticalTabsEvents>(type: K, callback: (e: SntVerticalTabsEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<SntVerticalTabsProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { getWebComponent: 1 });
	}

	get getWebComponent(): HTMLSntVerticalTabsElement | undefined {
		return this.$$.ctx[1];
	}
}

export default SntVerticalTabs;