/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface StencilAsyncContentProps {
  
  /**  */
  documentLocation?: Components.StencilAsyncContent["documentLocation"]
}

interface StencilAsyncContentEvents {
  
}

interface StencilAsyncContentSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let stencil_async_content;
	let current;
	const default_slot_template = /*#slots*/ ctx[4].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[3], null);

	return {
		c() {
			stencil_async_content = element("stencil-async-content");
			if (default_slot) default_slot.c();
			set_custom_element_data(stencil_async_content, "document-location", /*documentLocation*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, stencil_async_content, anchor);

			if (default_slot) {
				default_slot.m(stencil_async_content, null);
			}

			/*stencil_async_content_binding*/ ctx[5](stencil_async_content);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 8) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[3], dirty, null, null);
				}
			}

			if (!current || dirty & /*documentLocation*/ 1) {
				set_custom_element_data(stencil_async_content, "document-location", /*documentLocation*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(stencil_async_content);
			if (default_slot) default_slot.d(detaching);
			/*stencil_async_content_binding*/ ctx[5](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { documentLocation = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function stencil_async_content_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("documentLocation" in $$props) $$invalidate(0, documentLocation = $$props.documentLocation);
		if ("$$scope" in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	return [
		documentLocation,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		stencil_async_content_binding
	];
}

class StencilAsyncContent extends SvelteComponent {
  $$prop_def: StencilAsyncContentProps;
  $$events_def: StencilAsyncContentEvents;
  $$slot_def: StencilAsyncContentSlots;

  $on<K extends keyof StencilAsyncContentEvents>(type: K, callback: (e: StencilAsyncContentEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<StencilAsyncContentProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { documentLocation: 0, getWebComponent: 2 });
	}

	get getWebComponent(): HTMLStencilAsyncContentElement | undefined {
		return this.$$.ctx[2];
	}
}

export default StencilAsyncContent;