/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from 'component-library';


interface StencilRouterPromptProps {
  
  /**  */
  when?: Components.StencilRouterPrompt["when"]
  
  /**  */
  message?: Components.StencilRouterPrompt["message"]
  
  /**  */
  history?: Components.StencilRouterPrompt["history"]
}

interface StencilRouterPromptEvents {
  
}

interface StencilRouterPromptSlots {
  default: any
}
  
/* generated by Svelte v3.35.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let stencil_router_prompt;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			stencil_router_prompt = element("stencil-router-prompt");
			if (default_slot) default_slot.c();
			set_custom_element_data(stencil_router_prompt, "when", /*when*/ ctx[0]);
			set_custom_element_data(stencil_router_prompt, "message", /*message*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, stencil_router_prompt, anchor);

			if (default_slot) {
				default_slot.m(stencil_router_prompt, null);
			}

			/*stencil_router_prompt_binding*/ ctx[8](stencil_router_prompt);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 64) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[6], dirty, null, null);
				}
			}

			if (!current || dirty & /*when*/ 1) {
				set_custom_element_data(stencil_router_prompt, "when", /*when*/ ctx[0]);
			}

			if (!current || dirty & /*message*/ 2) {
				set_custom_element_data(stencil_router_prompt, "message", /*message*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(stencil_router_prompt);
			if (default_slot) default_slot.d(detaching);
			/*stencil_router_prompt_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { when = undefined } = $$props;
	let { message = undefined } = $$props;
	let { history = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		$$invalidate(5, __mounted = true);
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function stencil_router_prompt_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("when" in $$props) $$invalidate(0, when = $$props.when);
		if ("message" in $$props) $$invalidate(1, message = $$props.message);
		if ("history" in $$props) $$invalidate(3, history = $$props.history);
		if ("$$scope" in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*__mounted, history*/ 40) {
			$: if (__mounted) setProp("history", history);
		}
	};

	return [
		when,
		message,
		__ref,
		history,
		getWebComponent,
		__mounted,
		$$scope,
		slots,
		stencil_router_prompt_binding
	];
}

class StencilRouterPrompt extends SvelteComponent {
  $$prop_def: StencilRouterPromptProps;
  $$events_def: StencilRouterPromptEvents;
  $$slot_def: StencilRouterPromptSlots;

  $on<K extends keyof StencilRouterPromptEvents>(type: K, callback: (e: StencilRouterPromptEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<StencilRouterPromptProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			when: 0,
			message: 1,
			history: 3,
			getWebComponent: 4
		});
	}

	get getWebComponent(): HTMLStencilRouterPromptElement | undefined {
		return this.$$.ctx[4];
	}
}

export default StencilRouterPrompt;